### ISSUE TITLE
Suggest Topics for November (2019.11.19) Pan-PMCs Meeting

### ISSUE THREAD

**Issue by brooklynrob** [finos/finos-pmcs#14]
See draft at https://github.com/finos/finos-pmcs/blob/master/docs/2019-11-19-Pan-PMC-Meeting.md

**Comment by brooklynrob** [comment]
My suggestions: 
- Board Meeting Debrief
  - Upcoming GS Contribution Announcement
- FINOS [Project Revised Lifecycle Stages](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/1158053892/RFC+Revised+Project+Lifecycle) (Approved by Board in July)
  - Program Stewardship Responsibilities of Projects ("Up or Out" --> Get to 'Active' in a Year or Archive)

**Comment by brooklynrob** [comment]
Another topic: The new and enhanced vulnerability scanning and reporting tool we plan to roll out to the FINOS programs and projects after the New Year, along with implications and benefits of these tools. (CC @maoo @mcleo-d @mindthegab)

**Comment by mindthegab** [comment]
I would like to also cover the importance of "public task tracking" in github and marking "good first issues" as a unified practice to garner "organic" contribution. 

I'm happy to speak to it, since we're more and more using this well-established open source pattern in our resources, e.g. https://www.finos.org/get-involved
